# Generated by Django 4.2.6 on 2023-10-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksdatabase', '0008_load_fixtures'),
        ('main', '0001_initial'),
        ('report', '0002_report_book_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_book', to='booksdatabase.book'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_user', to='main.user'),
        ),
    ]
