# Generated by Django 4.2.6 on 2023-10-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_alter_report_book_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='book_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
