# Generated by Django 4.2.6 on 2023-10-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_book_post_date_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
