# Generated by Django 4.2.6 on 2023-10-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("authors", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("published_date", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("categories", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("preview_link", models.URLField(blank=True, null=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="covers")),
                ("isbn_10", models.CharField(blank=True, max_length=10, null=True)),
                ("isbn_13", models.CharField(blank=True, max_length=13, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
