# Generated by Django 4.2.6 on 2023-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_publish_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='published_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
