# Generated by Django 4.2.6 on 2023-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksdatabase', '0009_delete_rating'),
        ('publish', '0005_alter_publish_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='booksdatabase.author'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='booksdatabase.category'),
        ),
    ]
