# Generated by Django 4.2.6 on 2023-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_alter_publish_authors_alter_publish_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='categories',
        ),
        migrations.AddField(
            model_name='publish',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
