# Generated by Django 4.2.6 on 2023-10-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
