# Generated by Django 4.2.6 on 2023-10-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("publisher", models.CharField(max_length=255)),
                ("published_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("page_count", models.IntegerField()),
                ("language", models.CharField(max_length=255)),
                ("preview_link", models.URLField()),
                ("cover_link", models.URLField(blank=True, null=True)),
                ("industry_identifiers", models.JSONField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books_authored", to="booksdatabase.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_books",
                        to="booksdatabase.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                related_name="books_in_category", to="booksdatabase.category"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors_books",
                to="booksdatabase.book",
            ),
        ),
    ]
