# Generated by Django 4.2.6 on 2023-10-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksdatabase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_link",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers"),
        ),
    ]
