# Generated by Django 4.2.6 on 2023-10-27 08:29

import os
from django.db import migrations
from django.conf import settings
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "initial_data.json")
    
    # Copy the images to the media folder
    fixtures_dir = os.path.join(settings.BASE_DIR, "booksdatabase", "fixtures", "covers")
    media_dir = os.path.join(settings.BASE_DIR, "media", "covers")
    # Make sure the media folder exists
    os.makedirs(media_dir, exist_ok=True)
    for filename in os.listdir(fixtures_dir):
        src = os.path.join(fixtures_dir, filename)
        dst = os.path.join(media_dir, filename)
        # Copy the file
        with open(src, "rb") as fsrc:
            with open(dst, "wb") as fdst:
                fdst.write(fsrc.read())

class Migration(migrations.Migration):
    dependencies = [
        ("booksdatabase", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
