# Generated by Django 4.2.6 on 2023-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksdatabase", "0002_remove_book_cover_link_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="industry_identifiers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="page_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="preview_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
