# Generated by Django 4.2.6 on 2023-10-25 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "booksdatabase",
            "0003_alter_book_industry_identifiers_alter_book_language_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="book",
        ),
        migrations.RemoveField(
            model_name="category",
            name="book",
        ),
    ]
