# Generated by Django 4.2.6 on 2023-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksdatabase", "0004_remove_author_book_remove_category_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="industry_identifiers",
        ),
        migrations.AddField(
            model_name="book",
            name="isbn_10",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn_13",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
