# Generated by Django 4.2.6 on 2023-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booksdatabase",
            "0005_remove_book_industry_identifiers_book_isbn_10_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
