# Generated by Django 4.2.6 on 2023-10-26 08:22

from django.db import migrations, models

def convert_published_date(apps, schema_editor):
    Book = apps.get_model('booksdatabase', 'Book')
    for book in Book.objects.all():
        if book.published_date:
            book.published_date = book.published_date.split('-')[0]
            book.published_date = int(book.published_date)
            book.save()

class Migration(migrations.Migration):
    dependencies = [
        (
            "booksdatabase",
            "0005_remove_book_industry_identifiers_book_isbn_10_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(convert_published_date),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
