# Generated by Django 4.2.6 on 2023-10-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksdatabase', '0008_load_fixtures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
