# Generated by Django 4.2.6 on 2023-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksdatabase', '0008_load_fixtures'),
        ('MyBooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybook',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='Book',
        ),
        migrations.AddField(
            model_name='mybook',
            name='Book',
            field=models.ManyToManyField(blank=True, null=True, to='booksdatabase.book'),
        ),
    ]
