# Generated by Django 4.2.6 on 2023-10-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBooks', '0002_rename_user_mybook_user_remove_mybook_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='Book',
        ),
    ]
