# Generated by Django 4.2.6 on 2023-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksdatabase', '0008_load_fixtures'),
        ('MyBooks', '0003_remove_mybook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='books',
            field=models.ManyToManyField(related_name='books', to='booksdatabase.book'),
        ),
    ]
