# Generated by Django 4.2.6 on 2023-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBooks', '0005_remove_review_mybook_remove_review_score_review_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
