# Generated by Django 4.2.6 on 2023-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBooks', '0006_review_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
