# Generated by Django 4.2.6 on 2023-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBooks', '0007_alter_mybook_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
